// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrcZqXecSI9sNLX-EibQEeUY4vD8K1fI',
    appId: '1:680093072583:web:0b327d0fc287b5bfdd12e2',
    messagingSenderId: '680093072583',
    projectId: 'project-firebase-imprv',
    authDomain: 'project-firebase-imprv.firebaseapp.com',
    storageBucket: 'project-firebase-imprv.firebasestorage.app',
    measurementId: 'G-20PN00RY55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnw8Ujn7w8CKtlkz26qU6onrGivPo9xQY',
    appId: '1:680093072583:android:9155bd730f98bce1dd12e2',
    messagingSenderId: '680093072583',
    projectId: 'project-firebase-imprv',
    storageBucket: 'project-firebase-imprv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9A5zsoN6Pvg-QdTtO6ONmxpduei0pzx4',
    appId: '1:680093072583:ios:4452994ab2537146dd12e2',
    messagingSenderId: '680093072583',
    projectId: 'project-firebase-imprv',
    storageBucket: 'project-firebase-imprv.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebaseImprv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9A5zsoN6Pvg-QdTtO6ONmxpduei0pzx4',
    appId: '1:680093072583:ios:4452994ab2537146dd12e2',
    messagingSenderId: '680093072583',
    projectId: 'project-firebase-imprv',
    storageBucket: 'project-firebase-imprv.firebasestorage.app',
    iosBundleId: 'com.example.projectFirebaseImprv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWrcZqXecSI9sNLX-EibQEeUY4vD8K1fI',
    appId: '1:680093072583:web:687472fae4a560a5dd12e2',
    messagingSenderId: '680093072583',
    projectId: 'project-firebase-imprv',
    authDomain: 'project-firebase-imprv.firebaseapp.com',
    storageBucket: 'project-firebase-imprv.firebasestorage.app',
    measurementId: 'G-S0KZJY89N5',
  );
}
